/**
 * HighS
 * First Demonstration.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wujood@gmx.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HighscoreBoardEntry } from './highscoreBoardEntry';


export interface HighscoreBoard {
    id?: number;
    name?: string;
    entries?: Array<HighscoreBoardEntry>;
}
