/**
 * HighS
 * First Demonstration.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: wujood@gmx.de
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { HighscoreBoard } from '../model/highscoreBoard';
import { HighscoreBoardCreatedResponse } from '../model/highscoreBoardCreatedResponse';
import { HighscoreBoardEntry } from '../model/highscoreBoardEntry';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class HighscoreService {

    protected basePath = 'http://wujood.ddns.net:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (let consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * Add a new highscoreboard to the database
     * 
     * @param highscoreBoard The name of the Highscore Board that will be created. (This is not a ID of any sort!)
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addHighscoreBoard(highscoreBoard?: HighscoreBoard, observe?: 'body', reportProgress?: boolean): Observable<HighscoreBoardCreatedResponse>;
    public addHighscoreBoard(highscoreBoard?: HighscoreBoard, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<HighscoreBoardCreatedResponse>>;
    public addHighscoreBoard(highscoreBoard?: HighscoreBoard, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<HighscoreBoardCreatedResponse>>;
    public addHighscoreBoard(highscoreBoard?: HighscoreBoard, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<HighscoreBoardCreatedResponse>(`${this.basePath}/highscore`,
            highscoreBoard,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Find HighscoreBoard by ID
     * Returns a single HighscoreBoard
     * @param highscoreId ID of HighscoreBoard to return
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getHighscoreBoardById(highscoreId: number, observe?: 'body', reportProgress?: boolean): Observable<HighscoreBoard>;
    public getHighscoreBoardById(highscoreId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<HighscoreBoard>>;
    public getHighscoreBoardById(highscoreId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<HighscoreBoard>>;
    public getHighscoreBoardById(highscoreId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (highscoreId === null || highscoreId === undefined) {
            throw new Error('Required parameter highscoreId was null or undefined when calling getHighscoreBoardById.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
        ];

        return this.httpClient.get<HighscoreBoard>(`${this.basePath}/highscore/${encodeURIComponent(String(highscoreId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * Inserts a new entry into the highscore board.
     * 
     * @param highscoreId ID of HighscoreBoard to return
     * @param highscoreBoardEntry Entry to a HighscoreBoard
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public newEntry(highscoreId: number, highscoreBoardEntry?: HighscoreBoardEntry, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public newEntry(highscoreId: number, highscoreBoardEntry?: HighscoreBoardEntry, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public newEntry(highscoreId: number, highscoreBoardEntry?: HighscoreBoardEntry, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public newEntry(highscoreId: number, highscoreBoardEntry?: HighscoreBoardEntry, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (highscoreId === null || highscoreId === undefined) {
            throw new Error('Required parameter highscoreId was null or undefined when calling newEntry.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        let httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set("Accept", httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json'
        ];
        let httpContentTypeSelected:string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected != undefined) {
            headers = headers.set("Content-Type", httpContentTypeSelected);
        }

        return this.httpClient.post<any>(`${this.basePath}/highscore/${encodeURIComponent(String(highscoreId))}`,
            highscoreBoardEntry,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
